#Logstash 监听 4560 端口接收来自应用程序的日志 使用 json_lines 编解码器处理 JSON 格式的日志
input {
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 4560
    codec => json_lines
    type => "info"
  }
}
filter {}
# 将处理后的日志发送到 Elasticsearch
output {
  elasticsearch {
      action => "index"
      hosts => "es:9200"
      index => "group-buy-market-log-%{+YYYY.MM.dd}"#这里映射的日志索引
    }
}
